name: utilities_example
version: 1.0.0
description: "Comprehensive example showcasing the utilities package."
repository: "https://github.com/helpisdev/utilities_example.git"
homepage: "https://github.com/helpisdev/utilities_example"
issueTracker: "https://github.com/helpisdev/utilities_example/issues"
publish_to: none

# dart pub global activate derry
scripts:
  regenerate_goldens: flutter test --update-goldens --tags=golden
  gen:build:prepare: "flutter clean && flutter packages pub get"
  gen:build: dart run build_runner build --delete-conflicting-outputs
  gen:build:post: flutter pub get
  gen:build:complete: "derry gen:build:prepare && derry gen:build && derry gen:build:post"
  gen:watch: flutter pub run build_runner watch --delete-conflicting-outputs
  git:init: derry git:pull && derry git:submodule:init
  git:push: git push --recurse-submodules=on-demand --follow-tags
  git:pull: git pull origin main
  git:submodule:init: git submodule init && git submodule update && derry git:submodule:pull
  git:submodule:push: git submodule foreach 'git push'
  git:submodule:pull: git submodule update --remote --rebase
  git:submodule:checkout: git submodule foreach 'git checkout -b main'
  project:setup: derry git:init && melos bs && melos run get && derry gen:build:complete

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  accessibility_tools: ^1.0.0
  adaptive_scaffold:
    git:
      url: https://github.com/helpisdev/adaptive_scaffold.git
      ref: main
  after_layout: ^1.2.0
  app_links: ^3.4.3
  audio_session: ^0.1.16
  autoequal: ^0.5.1
  collection: ^1.17.2
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.4
  flutter_svg: ^2.0.7
  flutter_web_plugins:
    sdk: flutter
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  handy_window: ^0.3.1
  intl: ^0.18.1
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  just_audio_mpv: ^0.1.6
  just_audio_windows: ^0.2.0
  logger: ^2.0.1
  lottie: ^2.4.0
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.4.2
  platform: ^3.1.0
  rive: ^0.11.4
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  universal_io: ^2.2.2
  upgrader: ^8.1.0
  url_launcher: ^6.1.12
  utilities:
    git:
      url: https://github.com/helpisdev/utilities.git
      ref: main
  uuid: ^3.0.7

dev_dependencies:
  alchemist: ^0.6.1
  autoequal_gen: ^0.5.1
  # bdd_widget_test: ^1.6.0
  build_runner: ^2.4.6
  # build_test: ^2.2.0
  build_web_compilers: ^4.0.4
  checked_yaml: ^2.0.3
  # flutter_driver:
  #   sdk: flutter
  flutter_flavorizr: ^2.2.1
  flutter_gen_runner: ^5.3.1
  # flutter_goldens:
  #   sdk: flutter
  # flutter_test:
  #   sdk: flutter
  go_router_builder: ^2.2.0
  icons_launcher: ^2.1.3
  # integration_test:
  #   sdk: flutter
  melos: ^3.1.0
  # mocktail: ^1.0.0
  # spec: ^0.2.3
  # test: ^1.24.4

dependency_overrides:
  collection: ^1.18.0
  crypto: ^3.0.3
  intl: ^0.18.1
  # matcher: ^0.12.16
  # test_api: ^0.6.1

flutter:
  uses-material-design: true
  # Enable generation of localized Strings from arb files.
  # uncomment the next line to generate a synthetic-package, change the equivalent in l10n.yaml
  # generate: true
  assets:
    - assets/
    - assets/image/
    # - assets/image/vector/
    # - assets/image/raster/
    - assets/image/data/
    - assets/image/data/stream1_base64_data.txt
    - assets/image/data/stream2_base64_data.txt
    - assets/image/data/stream3_base64_data.txt
    # - assets/multimedia/
    # - assets/multimedia/audio/
    # - assets/multimedia/video/
    # - assets/pdf/
    # - assets/font/
    - assets/color/
    - assets/color/colors.xml
    # - assets/txt/
    # - assets/animation/
    # - assets/animation/rive/
    # - assets/animation/lottie/
    - assets/l10n/
    - assets/l10n/arb/
    - assets/l10n/arb/app_en.arb
    - assets/l10n/arb/app_el.arb
#  fonts:
#    - family: Comfortaa
#      fonts:
#        - asset: assets/fonts/comfortaa.ttf

flutter_gen:
  output: lib/src/gen/assets
  line_length: 80
  gen_for_package: true
  integrations:
    flutter_svg: true
    rive: true
    lottie: true
  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flavorizr:
  ide: vscode
  instructions:
    [
      assets:download,
      assets:extract,
      assets:clean,
      android:buildGradle,
      android:androidManifest,
      android:icons,
      ios:icons,
      ios:plist,
    ]
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    development:
      app:
        name: "Utilities Example Development"

      android:
        applicationId: "dev.helpis.utilities_example.development"

      ios:
        bundleId: "dev.helpis.utilities_example.development"

    production:
      app:
        name: "Utilities Example Production"

      android:
        applicationId: "dev.helpis.utilities_example.production"

      ios:
        bundleId: "dev.helpis.utilities_example.production"
